language: node_js

cache:
  yarn: true

notifications:
  slack:
    rooms:
      - settlemint:5QuOPa3Z4kJbfbNIgei0asur#mint

node_js:
  - "12"

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - yarn

after_success:
  - yarn build
  - yarn run semantic-release
